/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_IC_PROXY_HPP_
#define V0_COMMONAPI_IC_PROXY_HPP_

#include <v0/commonapi/ICProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class ICProxy
    : virtual public IC,
      virtual public ICProxyBase,
      virtual public _AttributeExtensions... {
public:
    ICProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ICProxy();

    typedef ::v0::commonapi::IC InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls setGear with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void setGear(std::string _gear, CommonAPI::CallStatus &_internalCallStatus, int32_t &_result, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setGear with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> setGearAsync(const std::string &_gear, SetGearAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getBattery with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getBattery(CommonAPI::CallStatus &_internalCallStatus, int32_t &_battery, int32_t &_result, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getBattery with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getBatteryAsync(GetBatteryAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setMode with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void setMode(int32_t _mode, CommonAPI::CallStatus &_internalCallStatus, int32_t &_result, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setMode with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> setModeAsync(const int32_t &_mode, SetModeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast batteryStatusChanged.
     */
    virtual BatteryStatusChangedEvent& getBatteryStatusChangedEvent() {
        return delegate_->getBatteryStatusChangedEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast gearStatusChanged.
     */
    virtual GearStatusChangedEvent& getGearStatusChangedEvent() {
        return delegate_->getGearStatusChangedEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast lrSignStatusChanged.
     */
    virtual LrSignStatusChangedEvent& getLrSignStatusChangedEvent() {
        return delegate_->getLrSignStatusChangedEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast pdcStatusChanged.
     */
    virtual PdcStatusChangedEvent& getPdcStatusChangedEvent() {
        return delegate_->getPdcStatusChangedEvent();
    }



 private:
    std::shared_ptr< ICProxyBase> delegate_;
};

typedef ICProxy<> ICProxyDefault;


//
// ICProxy Implementation
//
template <typename ... _AttributeExtensions>
ICProxy<_AttributeExtensions...>::ICProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ICProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ICProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ICProxy<_AttributeExtensions...>::~ICProxy() {
}

template <typename ... _AttributeExtensions>
void ICProxy<_AttributeExtensions...>::setGear(std::string _gear, CommonAPI::CallStatus &_internalCallStatus, int32_t &_result, const CommonAPI::CallInfo *_info) {
    delegate_->setGear(_gear, _internalCallStatus, _result, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ICProxy<_AttributeExtensions...>::setGearAsync(const std::string &_gear, SetGearAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->setGearAsync(_gear, _callback, _info);
}
template <typename ... _AttributeExtensions>
void ICProxy<_AttributeExtensions...>::getBattery(CommonAPI::CallStatus &_internalCallStatus, int32_t &_battery, int32_t &_result, const CommonAPI::CallInfo *_info) {
    delegate_->getBattery(_internalCallStatus, _battery, _result, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ICProxy<_AttributeExtensions...>::getBatteryAsync(GetBatteryAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getBatteryAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void ICProxy<_AttributeExtensions...>::setMode(int32_t _mode, CommonAPI::CallStatus &_internalCallStatus, int32_t &_result, const CommonAPI::CallInfo *_info) {
    delegate_->setMode(_mode, _internalCallStatus, _result, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ICProxy<_AttributeExtensions...>::setModeAsync(const int32_t &_mode, SetModeAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->setModeAsync(_mode, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &ICProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ICProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ICProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ICProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ICProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ICProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_IC_PROXY_HPP_
