/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_IC_PROXY_BASE_HPP_
#define V0_COMMONAPI_IC_PROXY_BASE_HPP_

#include <v0/commonapi/IC.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

class ICProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        int32_t
    > BatteryStatusChangedEvent;
    typedef CommonAPI::Event<
        std::string
    > GearStatusChangedEvent;
    typedef CommonAPI::Event<
        int32_t
    > LrSignStatusChangedEvent;
    typedef CommonAPI::Event<
        int32_t
    > PdcStatusChangedEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const int32_t&)> SetGearAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const int32_t&, const int32_t&)> GetBatteryAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const int32_t&)> SetModeAsyncCallback;

    virtual void setGear(std::string _gear, CommonAPI::CallStatus &_internalCallStatus, int32_t &_result, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> setGearAsync(const std::string &_gear, SetGearAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void getBattery(CommonAPI::CallStatus &_internalCallStatus, int32_t &_battery, int32_t &_result, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getBatteryAsync(GetBatteryAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void setMode(int32_t _mode, CommonAPI::CallStatus &_internalCallStatus, int32_t &_result, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> setModeAsync(const int32_t &_mode, SetModeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual BatteryStatusChangedEvent& getBatteryStatusChangedEvent() = 0;
    virtual GearStatusChangedEvent& getGearStatusChangedEvent() = 0;
    virtual LrSignStatusChangedEvent& getLrSignStatusChangedEvent() = 0;
    virtual PdcStatusChangedEvent& getPdcStatusChangedEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_IC_PROXY_BASE_HPP_
