/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_IC_STUB_HPP_
#define V0_COMMONAPI_IC_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/commonapi/IC.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service IC. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class ICStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual IC {
 public:
    /**
    * Sends a broadcast event for batteryStatusChanged. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireBatteryStatusChangedEvent(const int32_t &_batValue) = 0;
    /**
    * Sends a broadcast event for gearStatusChanged. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireGearStatusChangedEvent(const std::string &_gearValue) = 0;
    /**
    * Sends a broadcast event for lrSignStatusChanged. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireLrSignStatusChangedEvent(const int32_t &_signValue) = 0;
    /**
    * Sends a broadcast event for pdcStatusChanged. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void firePdcStatusChangedEvent(const int32_t &_distValue) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for IC.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ICStubRemoteEvent
{
public:
    virtual ~ICStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service IC to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ICStub
    : public virtual CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>
{
public:
    typedef std::function<void (int32_t _result)> setGearReply_t;
    typedef std::function<void (int32_t _battery, int32_t _result)> getBatteryReply_t;
    typedef std::function<void (int32_t _result)> setModeReply_t;

    virtual ~ICStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 7);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method setGear.
    virtual void setGear(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _gear, setGearReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method getBattery.
    virtual void getBattery(const std::shared_ptr<CommonAPI::ClientId> _client, getBatteryReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method setMode.
    virtual void setMode(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _mode, setModeReply_t _reply) = 0;
    /// Sends a broadcast event for batteryStatusChanged.
    virtual void fireBatteryStatusChangedEvent(const int32_t &_batValue) {
        auto stubAdapter = CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireBatteryStatusChangedEvent(_batValue);
    }
    /// Sends a broadcast event for gearStatusChanged.
    virtual void fireGearStatusChangedEvent(const std::string &_gearValue) {
        auto stubAdapter = CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireGearStatusChangedEvent(_gearValue);
    }
    /// Sends a broadcast event for lrSignStatusChanged.
    virtual void fireLrSignStatusChangedEvent(const int32_t &_signValue) {
        auto stubAdapter = CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireLrSignStatusChangedEvent(_signValue);
    }
    /// Sends a broadcast event for pdcStatusChanged.
    virtual void firePdcStatusChangedEvent(const int32_t &_distValue) {
        auto stubAdapter = CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->firePdcStatusChangedEvent(_distValue);
    }


    using CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef ICStubRemoteEvent RemoteEventType;
    typedef ::v0::commonapi::IC StubInterface;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_IC_STUB_HPP_
