/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_IC_inter_STUB_DEFAULT_HPP_
#define V0_COMMONAPI_IC_inter_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/commonapi/IC_interStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace commonapi {

/**
 * Provides a default implementation for IC_interStubRemoteEvent and
 * IC_interStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT IC_interStubDefault
    : public virtual IC_interStub {
public:
    COMMONAPI_EXPORT IC_interStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(IC_inter::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT IC_interStubRemoteEvent* initStubAdapter(const std::shared_ptr< IC_interStubAdapter> &_adapter) {
        CommonAPI::Stub<IC_interStubAdapter, IC_interStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void setGear_inter(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _gear, setGear_interReply_t _reply) {
        (void)_client;
        (void)_gear;
        int32_t result = 0;
        _reply(result);
    }
    COMMONAPI_EXPORT virtual void setLrsign_inter(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _lrsign, setLrsign_interReply_t _reply) {
        (void)_client;
        (void)_lrsign;
        int32_t result = 0;
        _reply(result);
    }
    COMMONAPI_EXPORT virtual void fireGearStatusChangedEvent(const std::string &_gear) {
        IC_interStub::fireGearStatusChangedEvent(_gear);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual IC_interStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(IC_interStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        IC_interStubDefault *defaultStub_;
    };
protected:
    IC_interStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_IC_inter_STUB_DEFAULT
